build_from:
  all: "lscr.io/linuxserver/obsidian:latest"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Obsidian"
  org.opencontainers.image.description: "Web-based Obsidian Markdown editor integrated into Home Assistant"
  org.opencontainers.image.source: "https://github.com/iroQuai/HA-obsidian-addon"
  org.opencontainers.image.licenses: "MIT"

args: {}
