name: Obsidian
version: "1.0.0"
slug: obsidian
description: Web-based Obsidian Markdown editor integrated into Home Assistant
url: "https://github.com/iroQuai/HA-obsidian-addon/tree/main/obsidian"
arch:
  - aarch64
  - amd64
init: false
map:
  - addon_config:rw
  - data:rw
options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Amsterdam"
schema:
  PUID: int
  PGID: int
  TZ: str?
image: "lscr.io/linuxserver/obsidian:latest"
ports:
  3000/tcp: 3241  # containerpoort : host-poort
ports_description:
  3000/tcp: Web UI port
privileged: []
webui: "[PROTO:ssl]://[HOST]:[PORT:3241]"
stage: experimental
startup: services
