name: Obsidian
version: "latest"
slug: obsidian
description: Web-based Obsidian Markdown editor integrated into Home Assistant
url: "https://github.com/iroQuai/HA-obsidian-addon/tree/main/obsidian"
arch:
  - aarch64
  - amd64
init: false
legacy: true 
map:
  - addon_config:rw
  - data:rw
options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Amsterdam"
schema:
  PUID: int
  PGID: int
  TZ: Europe/Amsterdam 
image: "lscr.io/linuxserver/obsidian:latest"
ports:
  3000/tcp: 3241   # http (optioneel)
  3001/tcp: 3242   # https (aanbevolen)
ports_description:
  3000/tcp: Web UI (HTTP)
  3001/tcp: Web UI (HTTPS)
privileged: []
webui: "https://[HOST]:[PORT:3001]"
stage: experimental
startup: services